nlp_engine_name: spacy
models:
-
  lang_code: en
  model_name: en_core_web_lg
-
  lang_code: de
  model_name: de_core_news_lg
-
  lang_code: fr
  model_name: fr_core_news_lg
ner_model_configuration:
  model_to_presidio_entity_mapping:
    PERSON: PERSON
    LOC: LOCATION
    LOCATION: LOCATION
    GPE: LOCATION
    DATE: DATE_TIME
    TIME: DATE_TIME
    PHONE: PHONE_NUMBER
  low_confidence_score_multiplier: 0.4
  low_score_entity_names:
  - ORG
  default_score: 0.85
  labels_to_ignore:
  - O
